---
ID: "28782703-a551-4678-af18-0856fb25fbc6"
Parent: "ea862c43-f303-4273-8e88-fa7f8d7fbc76"
Template: "b04ab8f4-2bdc-42d0-b8e1-87186dc8bf9c"
Path: /sitecore/content/retail/brightco/Presentation/Enumerations/Products
BranchID: "c04abfd2-04f9-4e16-8303-8d4124d23f0c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E57DCA61-A762-4F75-A88A-E3F26E9D939D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251222T180631Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\angela.gustafson@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6f4820e7-7d44-4101-a6b3-de4708c8918b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\angela.gustafson@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251222T180631Z
